// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxphGfbo8NrYE9wGWZ9_uGYEtxvoIzV-k',
    appId: '1:6004964285:web:5390d448f5ecb003b8b0d4',
    messagingSenderId: '6004964285',
    projectId: 'yens-5ff6a',
    authDomain: 'yens-5ff6a.firebaseapp.com',
    storageBucket: 'yens-5ff6a.firebasestorage.app',
    measurementId: 'G-QN6VYSPYT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFjgp3ruodEGT6L520CWGsVYKjTtPpAw',
    appId: '1:6004964285:android:b56eb9851e5217ffb8b0d4',
    messagingSenderId: '6004964285',
    projectId: 'yens-5ff6a',
    storageBucket: 'yens-5ff6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0d7pOy6xGOqTtqPoeFqZPAYYFreCYdrk',
    appId: '1:6004964285:ios:25f0d2118fd8c845b8b0d4',
    messagingSenderId: '6004964285',
    projectId: 'yens-5ff6a',
    storageBucket: 'yens-5ff6a.firebasestorage.app',
    iosBundleId: 'com.example.yensss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0d7pOy6xGOqTtqPoeFqZPAYYFreCYdrk',
    appId: '1:6004964285:ios:25f0d2118fd8c845b8b0d4',
    messagingSenderId: '6004964285',
    projectId: 'yens-5ff6a',
    storageBucket: 'yens-5ff6a.firebasestorage.app',
    iosBundleId: 'com.example.yensss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxphGfbo8NrYE9wGWZ9_uGYEtxvoIzV-k',
    appId: '1:6004964285:web:0e04bc959e82b9feb8b0d4',
    messagingSenderId: '6004964285',
    projectId: 'yens-5ff6a',
    authDomain: 'yens-5ff6a.firebaseapp.com',
    storageBucket: 'yens-5ff6a.firebasestorage.app',
    measurementId: 'G-6G05F54GF8',
  );
}
